# Generated by Django 5.1.3 on 2024-12-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='rooms',
            field=models.IntegerField(default=1, verbose_name='Кількість кімнат'),
        ),
        migrations.AlterField(
            model_name='house',
            name='rooms',
            field=models.IntegerField(default=1, verbose_name='Кількість кімнат'),
        ),
    ]
